version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - sqlite_data:/var/www/sqlite_data
    environment:
      - TZ=${TZ:-UTC}
      - DEBUG=${DEBUG:-false}
    container_name: mark_it

volumes:
  sqlite_data:
